### ISSUE TITLE
🚨🚨本番環境（https://hirodai-kaede.com/）でCSRF token mismatch.が発生する🚨🚨

### ISSUE THREAD

**Issue by amoon46** [YamamotoNagito/l10dev#461]
講義コード検索時や新規登録時において，CSRF token mismatch.というエラーが発生する．

https://hirodaikaede.xsrv.jp/ では発生しない

<img width="1440" alt="スクリーンショット 2024-03-04 18 50 19" src="https://github.com/YamamotoNagito/l10dev/assets/74179935/62c66d1c-adde-48a4-a7e5-c780056de544">

**Comment by amoon46** [comment]
@YamamotoNagito 
@piro-hiroki 

マジで謝罪なんですが，エラー解消しようとしていじってたらxserverの方も何故かユーザー認証がうまくいかない状態になってしましいました🙇　ほんますいません．

格闘しすぎて訳わからんので助けて欲しいです！！！！！！！！！！！！！！！！！！！！！

**Comment by piro-hiroki** [comment]
明日の夜とか空いているのでやりましょう〜！

**Comment by amoon46** [comment]
@YamamotoNagito 
@piro-hiroki 

20時ぐらいから作業できます！

**Comment by piro-hiroki** [comment]
19時から行けます〜！

**Comment by amoon46** [comment]
@piro-hiroki 

作業の部屋(issue)のリンクに入ってます！

**Comment by amoon46** [comment]
@piro-hiroki 
今ってどんな状況ですか？？

**Comment by amoon46** [comment]
@piro-hiroki 
もしかして爆睡してます？？？

**Comment by amoon46** [comment]
@piro-hiroki 
今日は別にペアプロとかじゃない感じですかね？

エラー原因全然わかっていないので、別々だと自分あんまり進めれる部分ないかなって感じなんですが，，，

**Comment by piro-hiroki** [comment]
本当にごめんなさい、外出してました🙏🙏
明日なぎとの家に行くので、そのタイミングで原因探してみます🙏

**Comment by amoon46** [comment]
全然大丈夫です！爆睡してるんかと思ってました！

お願いします！ちなみに彼の家には現状wifiがないらしいです，，，

**Comment by amoon46** [comment]
@piro-hiroki 

ここのエラー解消できたらレビュー集めとかを進めていけそなので、空いている時間とかで確認していただけるとめっちゃありがたいです！！！！

**Comment by amoon46** [comment]
@piro-hiroki 

いけます！！！！

**Comment by piro-hiroki** [comment]
OKです
いつもの部屋に入ってます〜
https://meet.google.com/tfx-ymed-dde

**Comment by piro-hiroki** [comment]
解決！！！
