### ISSUE TITLE
リリースに向けた最終作業

### ISSUE THREAD

**Issue by amoon46** [YamamotoNagito/l10dev#473]
3/10, 3/11ぐらいにはリリースしたい

待ちに待ったリリースじゃー！！！！！

- [x] mainブランチへのマージ
- [x] DBの更新（不要なデータの削除）
- [x] デバック
- [x] バックアップの取り方の確認
- [x] アプリリリース

**Comment by piro-hiroki** [comment]
https://github.com/YamamotoNagito/l10dev/pull/441
